# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import map_matcher_pb2 as map__matcher__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in map_matcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MapMatcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MatchRoutes = channel.unary_unary(
                '/mapmatcher.MapMatcher/MatchRoutes',
                request_serializer=map__matcher__pb2.MatchRequest.SerializeToString,
                response_deserializer=map__matcher__pb2.MatchResponse.FromString,
                _registered_method=True)
        self.CalculateLapDistance = channel.unary_unary(
                '/mapmatcher.MapMatcher/CalculateLapDistance',
                request_serializer=map__matcher__pb2.LapDistanceRequest.SerializeToString,
                response_deserializer=map__matcher__pb2.LapDistanceResponse.FromString,
                _registered_method=True)
        self.FindTimesplitOnLap = channel.unary_unary(
                '/mapmatcher.MapMatcher/FindTimesplitOnLap',
                request_serializer=map__matcher__pb2.TimesplitOnLapRequest.SerializeToString,
                response_deserializer=map__matcher__pb2.TimesplitOnLapResponse.FromString,
                _registered_method=True)


class MapMatcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MatchRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateLapDistance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindTimesplitOnLap(self, request, context):
        """Find intersections between a timesplit (line) and a lap polyline.
        Returns list of intersections with the GPS point and its cumulative distance on the lap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapMatcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MatchRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchRoutes,
                    request_deserializer=map__matcher__pb2.MatchRequest.FromString,
                    response_serializer=map__matcher__pb2.MatchResponse.SerializeToString,
            ),
            'CalculateLapDistance': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateLapDistance,
                    request_deserializer=map__matcher__pb2.LapDistanceRequest.FromString,
                    response_serializer=map__matcher__pb2.LapDistanceResponse.SerializeToString,
            ),
            'FindTimesplitOnLap': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTimesplitOnLap,
                    request_deserializer=map__matcher__pb2.TimesplitOnLapRequest.FromString,
                    response_serializer=map__matcher__pb2.TimesplitOnLapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapmatcher.MapMatcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mapmatcher.MapMatcher', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MapMatcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MatchRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapmatcher.MapMatcher/MatchRoutes',
            map__matcher__pb2.MatchRequest.SerializeToString,
            map__matcher__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateLapDistance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapmatcher.MapMatcher/CalculateLapDistance',
            map__matcher__pb2.LapDistanceRequest.SerializeToString,
            map__matcher__pb2.LapDistanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindTimesplitOnLap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapmatcher.MapMatcher/FindTimesplitOnLap',
            map__matcher__pb2.TimesplitOnLapRequest.SerializeToString,
            map__matcher__pb2.TimesplitOnLapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
