# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map_matcher.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'map_matcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11map_matcher.proto\x12\nmapmatcher\"f\n\x0cMatchRequest\x12)\n\x0erecorded_route\x18\x01 \x03(\x0b\x32\x11.mapmatcher.Point\x12+\n\x10predefined_route\x18\x02 \x03(\x0b\x32\x11.mapmatcher.Point\"e\n\rMatchResponse\x12&\n\x07success\x18\x01 \x01(\x0b\x32\x13.mapmatcher.SuccessH\x00\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.mapmatcher.ErrorH\x00\x42\x08\n\x06result\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"G\n\x07Success\x12)\n\x0ematched_points\x18\x01 \x03(\x0b\x32\x11.mapmatcher.Point\x12\x11\n\tdistances\x18\x02 \x03(\x01\"=\n\x05\x45rror\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.mapmatcher.ErrorCode\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t*\x19\n\tErrorCode\x12\x0c\n\x08NO_MATCH\x10\x00\x32P\n\nMapMatcher\x12\x42\n\x0bMatchRoutes\x12\x18.mapmatcher.MatchRequest\x1a\x19.mapmatcher.MatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_matcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=422
  _globals['_ERRORCODE']._serialized_end=447
  _globals['_MATCHREQUEST']._serialized_start=33
  _globals['_MATCHREQUEST']._serialized_end=135
  _globals['_MATCHRESPONSE']._serialized_start=137
  _globals['_MATCHRESPONSE']._serialized_end=238
  _globals['_POINT']._serialized_start=240
  _globals['_POINT']._serialized_end=284
  _globals['_SUCCESS']._serialized_start=286
  _globals['_SUCCESS']._serialized_end=357
  _globals['_ERROR']._serialized_start=359
  _globals['_ERROR']._serialized_end=420
  _globals['_MAPMATCHER']._serialized_start=449
  _globals['_MAPMATCHER']._serialized_end=529
# @@protoc_insertion_point(module_scope)
