CREATE TABLE IF NOT EXISTS sport_kinds (
  id SERIAL PRIMARY KEY,
  code VARCHAR(100) NOT NULL
);

INSERT INTO sport_kinds (code) VALUES
('POOL_SWIMMING'),
('OPEN_WATER_SWIMMING'),
('ROAD_BIKE'),
('MTB'),
('ROAD_RUNNING'),
('TRAIL_RUNNING'),
('CROSS_COUNTRY_RUNNING');
